server {
    listen 80;
    listen [::]:80;
    server_name fitora.fitdnu.id.vn;
    client_max_body_size 50m;
    location ^~ /.well-known/acme-challenge/ { root /var/www/fitora-acme; }
    location / { return 301 https://$host$request_uri; }
}
