// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UserService.Infrastructure.Data;

#nullable disable

namespace UserService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260201000000_AddRequireJoinApproval")]
    partial class AddRequireJoinApproval
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserService.Domain.Models.Group", b =>
                {
                    b.Property<int>("Privacy").HasColumnType("int");
                    b.Property<bool>("RequireJoinApproval").HasColumnType("tinyint(1)");
                    b.Property<bool>("RequirePostApproval").HasColumnType("tinyint(1)");
                });
#pragma warning restore 612, 618
        }
    }
}
