version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hoang
      - MONGO_INITDB_ROOT_PASSWORD=123456@Aa
      - MONGO_INITDB_DATABASE=chatdb
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata: