name: Deploy Microservices to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build and Publish AuthService
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish --configuration Release --output ./publish/authservice --no-restore --no-build
        working-directory: ./Services/AuthService/AuthService.API
        shell: powershell

      - name: Build and Publish ChatService
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish --configuration Release --output ./publish/chatservice --no-restore --no-build
        working-directory: ./Services/ChatService/ChatService.API
        shell: powershell

      - name: Build and Publish InteractService
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish --configuration Release --output ./publish/interactservice --no-restore --no-build
        working-directory: ./Services/InteractService/InteractService.API
        shell: powershell

      - name: Build and Publish UserService
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish --configuration Release --output ./publish/userservice --no-restore --no-build
        working-directory: ./Services/UserService/UserService.API
        shell: powershell

      - name: Build and Publish ApiGateway
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish --configuration Release --output ./publish/apigateway --no-restore --no-build
        working-directory: ./ApiGateways/ApiGateway
        shell: powershell

      - name: Deploy to Windows Server
        run: |
          $ErrorActionPreference = "Stop"
          $privateKey = "${{ secrets.SSH_PRIVATE_KEY }}"
          $username = "${{ secrets.SERVER_USERNAME }}"
          $privateKeyPath = "C:\Users\$username\.ssh\id_rsa"
          Set-Content -Path $privateKeyPath -Value $privateKey
          chmod 600 $privateKeyPath
          $script = @'
            net stop was
            Remove-Item -Path C:\inetpub\wwwroot\authservice\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path C:\inetpub\wwwroot\chatservice\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path C:\inetpub\wwwroot\interactservice\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path C:\inetpub\wwwroot\userservice\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path C:\inetpub\wwwroot\apigateway\* -Recurse -Force -ErrorAction SilentlyContinue
            Copy-Item -Path ./publish/authservice/* -Destination C:\inetpub\wwwroot\authservice -Recurse
            Copy-Item -Path ./publish/chatservice/* -Destination C:\inetpub\wwwroot\chatservice -Recurse
            Copy-Item -Path ./publish/interactservice/* -Destination C:\inetpub\wwwroot\interactservice -Recurse
            Copy-Item -Path ./publish/userservice/* -Destination C:\inetpub\wwwroot\userservice -Recurse
            Copy-Item -Path ./publish/apigateway/* -Destination C:\inetpub\wwwroot\apigateway -Recurse
            net start w3svc
          '@
          ssh -i $privateKeyPath -o StrictHostKeyChecking=no -p 22 ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "powershell -Command `$script"
        shell: pwsh
