name: Deploy Microservices to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Verify Project Files
        run: |
          dir Services/AuthService/AuthService.API/*.csproj || echo "AuthService.API.csproj not found"
          dir Services/ChatService/ChatService.API/*.csproj || echo "ChatService.API.csproj not found"
          dir Services/InteractService/InteractService.API/*.csproj || echo "InteractService.API.csproj not found"
          dir Services/UserService/UserService.API/*.csproj || echo "UserService.API.csproj not found"
          dir ApiGateways/ApiGateway/*.csproj || echo "ApiGateway.csproj not found"
        shell: powershell

      - name: Build and Publish AuthService
        run: |
          dotnet restore Services/AuthService/AuthService.API/AuthService.API.csproj
          dotnet build Services/AuthService/AuthService.API/AuthService.API.csproj --configuration Release --no-restore
          dotnet publish Services/AuthService/AuthService.API/AuthService.API.csproj --configuration Release --output ./publish/authservice --no-restore --no-build
        shell: powershell

      - name: Build and Publish ChatService
        run: |
          dotnet restore Services/ChatService/ChatService.API/ChatService.API.csproj
          dotnet build Services/ChatService/ChatService.API/ChatService.API.csproj --configuration Release --no-restore
          dotnet publish Services/ChatService/ChatService.API/ChatService.API.csproj --configuration Release --output ./publish/chatservice --no-restore --no-build
        shell: powershell

      - name: Build and Publish InteractService
        run: |
          dotnet restore Services/InteractService/InteractService.API/InteractService.API.csproj
          dotnet build Services/InteractService/InteractService.API/InteractService.API.csproj --configuration Release --no-restore
          dotnet publish Services/InteractService/InteractService.API/InteractService.API.csproj --configuration Release --output ./publish/interactservice --no-restore --no-build
        shell: powershell

      - name: Build and Publish UserService
        run: |
          dotnet restore Services/UserService/UserService.API/UserService.API.csproj
          dotnet build Services/UserService/UserService.API/UserService.API.csproj --configuration Release --no-restore
          dotnet publish Services/UserService/UserService.API/UserService.API.csproj --configuration Release --output ./publish/userservice --no-restore --no-build
        shell: powershell

      - name: Build and Publish ApiGateway
        run: |
          dotnet restore ApiGateways/ApiGateway/ApiGateway.csproj
          dotnet build ApiGateways/ApiGateway/ApiGateway.csproj --configuration Release --no-restore
          dotnet publish ApiGateways/ApiGateway/ApiGateway.csproj --configuration Release --output ./publish/apigateway --no-restore --no-build
        shell: powershell

      - name: Deploy to Windows Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            net stop was
            Remove-Item -Path C:\inetpub\wwwroot\authservice\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path C:\inetpub\wwwroot\chatservice\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path C:\inetpub\wwwroot\interactservice\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path C:\inetpub\wwwroot\userservice\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path C:\inetpub\wwwroot\apigateway\* -Recurse -Force -ErrorAction SilentlyContinue
            Copy-Item -Path ./publish/authservice/* -Destination C:\inetpub\wwwroot\authservice -Recurse
            Copy-Item -Path ./publish/chatservice/* -Destination C:\inetpub\wwwroot\chatservice -Recurse
            Copy-Item -Path ./publish/interactservice/* -Destination C:\inetpub\wwwroot\interactservice -Recurse
            Copy-Item -Path ./publish/userservice/* -Destination C:\inetpub\wwwroot\userservice -Recurse
            Copy-Item -Path ./publish/apigateway/* -Destination C:\inetpub\wwwroot\apigateway -Recurse
            net start w3svc
          shell: powershell